# -*- coding: utf-8 -*-
"""Lab 9 Naive Bayes (Multinomial).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lS0hVQbe3r89X4y7SOC0Ae2gHu_dP-qi

Made by: Thai Vang, Robert Armenta

Dataset from: https://www.kaggle.com/datasets/himanshunakrani/naive-bayes-classification-data
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer

df = pd.read_csv('spam_ham_dataset.csv')
df.head()

df.tail()

emails = [
    # Spam emails
    "Subject: free money claim now",
    "Subject: win a free iphone today",
    "Subject: limited time offer click now",
    "Subject: you have won a lottery prize",
    "Subject: claim your cash reward immediately",
    "Subject: urgent act now to receive prize",
    "Subject: congratulations you are selected winner",

    # Not Spam
    "Subject: can we meet tomorrow for lunch",
    "Subject: please send me the report",
    "Subject: let's schedule a meeting this week",
    "Subject: are you available for a call today",
    "Subject: thanks for your help earlier",
    "Subject: please review the attached document",
    "Subject: can you update me on the project",
]

# labeling
labels = [1,1,1,1,1,1,1, #First 7 are spam
          0,0,0,0,0,0,0] #Last 7 are not spam

# Creating converter tool
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(emails)

print("=== STEP 3: Words converted to numbers ===")
print(f"Number of unique words found: {len(vectorizer.get_feature_names_out())}")
print(f"All unique words: {vectorizer.get_feature_names_out()}")
print()

# Creating blank model
model = MultinomialNB()

# Training Model
model.fit(X, labels)

print("=== STEP 4: Model trained! ===")
print()

# Generating new emails
new_emails = [
    "free cash prize win now",         # Looks like spam!
    "can we meet for coffee tomorrow",  # Looks like normal email
    "claim your free lottery ticket",  # Looks like spam!
    "please send me the project files", # Looks like normal email
]

# Converting new emails into numbers using the SAME vectorizer
X_new = vectorizer.transform(new_emails)

# Asking to make predictions
predictions = model.predict(X_new)

# Get the probability of each prediction
probabilities = model.predict_proba(X_new)

print("=== STEP 5 & 6: Predictions on new emails ===")
print()

for i, email in enumerate(new_emails):
    # predictions[i] is either 1 (spam) or 0 (not spam)
    result = "SPAM" if predictions[i] == 1 else "NOT SPAM"

    # probabilities[i][0] = probability of NOT spam
    # probabilities[i][1] = probability of spam
    prob_spam    = probabilities[i][1] * 100   # multiply by 100 to get percent
    prob_notspam = probabilities[i][0] * 100

    print(f"Email: '{email}'")
    print(f"  --> Prediction : {result}")
    print(f"  --> Spam chance: {prob_spam:.1f}%")
    print(f"  --> Ham  chance: {prob_notspam:.1f}%")
    print()

"""This code builds a simple email spam classifier using the Multinomial Naive Bayes algorithm. It starts by loading a dataset and then creates a small custom list of email subject lines labeled as spam (1) or not spam (0). The text data is converted into numerical features using a bag-of-words approach with CountVectorizer, which turns each unique word into a feature. The model is then trained on this transformed data using . After training, the model is tested on new email examples by converting them using the same vectorizer and predicting whether each is spam or not. It also outputs probability scores showing how confident the model is for both spam and non-spam classes, helping interpret how strongly each prediction was made."""