# -*- coding: utf-8 -*-
"""Lab 9 Naive Bayes (Gaussian).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pNkFFLewttB_pk26qX3_vYCEaC_GYwuv

Made by: Thai Vang, Robert Armenta

Dataset from: https://www.kaggle.com/datasets/himanshunakrani/naive-bayes-classification-data
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

df = pd.read_csv('Bayes.csv')
df

# Measurements and labels
X = df.drop('diabetes', axis=1)
y = df['diabetes']

# Dataset information
print(f"Total patients in dataset: {len(df)}")
print(f"Measurements per flower : {X.shape[1]} (glucose, blood pressure)")
print()

# Printing first 5 patients
print("First 5 patients (measurements):")
print(f"{'glucose':>10} {'blood pressure':>15}")
for i in range(5):
    print(f"{X.iloc[i, 0]:>10} {X.iloc[i, 1]:>15}")

# Splitting data into training and testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training set size: {len(X_train)} (model learns from these)")
print (f"Testing set size : {len(X_test)} (model gets graded on these)")
print()

# Creating and training an empty model
model = GaussianNB()
model.fit(X_train, y_train)

print("Model Trained!")
print()

# Testing model and accuracy
y_predicted = model.predict(X_test)
accuracy = accuracy_score(y_test, y_predicted)

# Accuracy of model
print(f"Accuracy: {accuracy * 100:.1f}%")
print(f"(Got {int(accuracy * len(y_test))} out of {len(y_test)} correct)")
print()

# Testing how accurate model is
# Confusion Matrix
cm = confusion_matrix(y_test, y_predicted)

plt.figure(figsize=(6,4))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=['Yes', 'No'],
    yticklabels=['Yes', 'No']
)

plt.xlabel('Predicted Diabetes', fontsize=12)
plt.ylabel('Actual Diabetes', fontsize=12)
plt.title('Confusion Matrix - Tumor Groups', fontsize=14)
plt.tight_layout()
plt.show()

new_test = [[56, 60]] # [glucose, bloodpressure]

# Prediction
prediction = model.predict(new_test)[0]

# Probabilities
probabilities = model.predict_proba(new_test)[0]

print(f"New measurements:")
print(f" Glucose: {new_test[0][0]}")
print(f" Bloodpressure : {new_test[0][1]}")
print(f"Probabilities:")
for i, name in enumerate(['No', 'Yes']):
    print(f"  {name}: {probabilities[i] * 100:.1f}%")
print()

"""This code uses Gaussian Naive Bayes to classify whether a patient has diabetes based on numerical features like glucose level and blood pressure. It loads a dataset, separates the features (X) and target label (y), and splits the data into training and testing sets to evaluate performance. The model is trained on the training data using , then tested on unseen data to calculate accuracy and generate a confusion matrix, which visually shows correct and incorrect predictions. Finally, the model is used to predict diabetes for a new patient input and outputs probability percentages for each class (diabetes or not), demonstrating how the model can be applied to real-world predictions."""